name: Update GitHub Stats

on:
  schedule:
    - cron: "0 0 * * *" # Run daily
  workflow_dispatch:
  push:
    branches:
      - main
      - master

jobs:
  update-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: GitHub Stats
        uses: lowlighter/metrics@latest
        with:
          filename: assets/github-stats.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: header, activity, community, repositories, metadata
          config_timezone: Asia/Kolkata
          config_theme: tokyonight
          repositories_affiliations: owner, collaborator, organization_member

      - name: Top Languages
        uses: lowlighter/metrics@latest
        with:
          filename: assets/top-langs.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_theme: tokyonight
          plugin_languages: yes
          plugin_languages_details: bytes-size, percentage
          plugin_languages_limit: 8
          repositories_affiliations: owner, collaborator, organization_member

      - name: Activity Graph
        uses: lowlighter/metrics@latest
        with:
          filename: assets/activity-graph.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: ""
          config_theme: tokyonight
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
